apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
  selector:
    matchLabels:
      app: postfix
  template:
    metadata:
      labels:
        app: postfix
    spec:
      automountServiceAccountToken: false
      restartPolicy: Always

      dnsConfig:
        options:
          - name: ndots
            value: "1"

      volumes:
        # create config map by running `kubectl create configmap postfix --from-file main.cf --from-file sasl_passwd.lmdb`
        - name: postfix
          configMap:
            name: postfix
            defaultMode: 0444

      containers:
        - name: postfix
          image: piccirello/postfix
          imagePullPolicy: Always
          resources:
            limits:
              cpu: ".5"
              memory: 512Mi
            requests:
              cpu: ".1"
              memory: 256Mi
          ports:
            - name: smtp
              containerPort: 25

          volumeMounts:
            - name: postfix
              mountPath: "/etc/postfix/main.cf"
              subPath: main.cf
              readOnly: true
            - name: postfix
              mountPath: "/etc/postfix/sasl_passwd.lmdb"
              subPath: sasl_passwd.lmdb
              readOnly: true

          readinessProbe:
            tcpSocket:
              port: 25
            periodSeconds: 10
            failureThreshold: 2

          livenessProbe:
            tcpSocket:
              port: 25
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 2

          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            runAsUser: 0
            runAsGroup: 0
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
              # TODO may be able to further reduce this
              add:
                - CHOWN
                - DAC_OVERRIDE
                - FOWNER
                - FSETID
                - KILL
                - NET_BIND_SERVICE
                - SETGID
                - SETUID

---

apiVersion: v1
kind: Service
metadata:
  name: postfix
spec:
  type: LoadBalancer
  selector:
    app: postfix
  ports:
    - protocol: TCP
      port: 25
      targetPort: 25
